### ISSUE TITLE
GitLab Geo is not supported with this license.

### ISSUE THREAD

**Issue by Warvox** [Lakr233/GitLab-License-Generator#2]
### **Good time of day!**

Unfortunately, this type of license does not support the ability of Gitlab Geo to work. Issues the following errors on the secondary site...
```
GitLab Geo is not supported with this license. Please contact the sales team: https://about.gitlab.com/sales.
```
AND
```
remote:
remote: ========================================================================
remote:
remote: Your current license does not have GitLab Geo add-on enabled.
remote:
remote: ========================================================================
remote:
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Perhaps someone managed to make Geo work. If so, I will be glad to find out the correct activation method.

**Peace to all!**

**Comment by Lakr233** [comment]
Would you mind send me a copy of your configuration file (eg: docker-compose.yml) so I can have a look?

**Comment by Warvox** [comment]
I have not used Docker-Composer or similar programs.  Gitlab instances are installed on physical servers that are on the local network. The servers are running Debian 11. I installed the Gitlab instances according to the official manuals for the GitLab package:
https://docs.gitlab.com/ee/topics/offline/quick_start_guide.html#download-the-gitlab-package
https://docs.gitlab.com/ee/administration/geo/setup/two_single_node_sites.html
It would be wonderful if you could send your variant of Geo mode activation.

Thank you in advance for your reply)

**Comment by Lakr233** [comment]
I've got this done. Give me a seconds I'll setup an action for this.

```
irb(main):009:0> License.feature_available?(:geo)
=> true
```

**Comment by Lakr233** [comment]
Would you like to have a try on this: https://github.com/Lakr233/GitLab-License-Generator/actions/runs/7331603665/artifacts/1135407726

**Comment by Warvox** [comment]
Thank you very much, it's working now.
Of course I had to tweak the bash script, but overall everything works fine.
I would also like to point out that when deploying Geo, you need to set a public key on all Gitlab instances.
