### ISSUE TITLE
Script not work

### ISSUE THREAD

**Issue by alles** [Lakr233/GitLab-License-Generator#3]
Hi.

Not work.

```
root@009eae9730d1:/usr/src/myapp# ./make.sh 
[*] fetching ruby gem version...
[*] gitlab-license version: 2.4.0

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

thanks.

**Comment by Warvox** [comment]
Hi!
Read carefully what the error says:
```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
To fix this you need to remove one key in the `make.sh` file. It should be like this:
```
tar -xf gitlab-license.gem
```

**Comment by Lakr233** [comment]
This script is designed for macOS, and it appears you are using it on a Linux system. I recommend you obtain the build artifacts from GitHub Actions.

**Comment by alles** [comment]
> This script is designed for macOS, and it appears you are using it on a Linux system. I recommend you obtain the build artifacts from GitHub Actions.

Yes. I use docker image debian ruby.

My inattention will ruin me.
I verified in the v16.7.0. This work it.
Thanks for all answers.
