### ISSUE TITLE
It say license invalid 

### ISSUE THREAD

**Issue by tbm98** [Lakr233/GitLab-License-Generator#4]
I have replaced /opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub by public.key

sudo cat /opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAreEfP/ncA1A5cuxBz7rS
0Z9DDxdSymLwt2OUSM5WJa+dVB3zSpQjinifdNZq+iHVt8toZBZZ02H3unbn8td0
rIifoj4oVpLhvnOAVjUn5tZeUX17tWMA+yyBpf6w6IFxeYBXFd14WOKEarS05U9B
59DjBxNqSm+GzhljHO7vvTKy2xXQQ7Fa702DZ7jwr4DJnL87bDXfarnYksuawqtK
wQbFHAOvxFj8ghBh1Gshap1abExD4l7QWxFMTCVOkLJmXiqfOi5KuMiaMsSUsCBN
QDE3A5aKvpwLGozsvpGRMy5Tt4SgHC7ZbgerBNe75olOoPDxZf7bBt0+O5A/UjK/
HwIDAQAB
-----END PUBLIC KEY-----
```

but still can not submit result.gitlab-license or license.json

**Comment by Lakr233** [comment]
You are going to fix that yourself.

**Comment by tbm98** [comment]
@Lakr233 
I install ubuntu 22.04 and install gitlab ee 16.8.0
and then I replace content of /opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub by public.key

Did I do any wrong step?

**Comment by tbm98** [comment]
public.key I was download from github action
