### ISSUE TITLE
The license key is invalid

### ISSUE THREAD

**Issue by daniglyk** [Lakr233/GitLab-License-Generator#7]
I did all the steps indicated in the documentation.
But when I try to upload the key to gitlab, I see
![image](https://github.com/Lakr233/GitLab-License-Generator/assets/103996101/668df8d9-3b95-4a40-b0a4-1f093663ee06)

version of my gitlab - v16.9.2-ee

**Comment by Lakr233** [comment]
You need to resolve this issue yourself.
